# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

stages:
  - stage: build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Cache@2
            inputs:
              key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
              path: $(pnpm_config_cache)
            displayName: Cache pnpm

          - script: |
              curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
              pnpm config set store-dir $(pnpm_config_cache)
            displayName: "Setup pnpm"
          - script: |
              pnpm install
              pnpm run build
            displayName: "pnpm install and build"
          - task: CopyFiles@2
            displayName: "Copy files"
            inputs:
              Contents: |
                **\**
                !**\node_modules\**
              TargetFolder: '$(Build.BinariesDirectory)'
          - task: PublishBuildArtifacts@1
            condition: succeededOrFailed()
            inputs:
              PathtoPublish: '$(Build.BinariesDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: upload_static_files
    dependsOn: build
    condition: |
      in(dependencies.build.result, 'Succeeded', 'SucceededWithIssues')
    jobs:
      - job: upload_static_files
        displayName: Upload static files
        steps:
          - checkout: none
          - download: current
            artifact: drop
          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWS Pipes'
              regionName: 'us-east-1'
              bucketName: 'dev-mutte0-idp'
              sourceFolder: '$(Pipeline.Workspace)/drop/out'
              globExpressions: '_next/**'
              filesAcl: 'public-read'

  - stage: deploy_prd
    jobs:
      - deployment: Deploy
        environment: "prd"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - task: NodeTool@0
                  displayName: "Use Node 16.x"
                  inputs:
                    versionSpec: '16.x'