# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
      - develop
      - release/qa

pool:
  vmImage: ubuntu-latest

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  BRANCH_NAME: $(Build.SourceBranchName)

stages:
  - stage: build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: NodeTool@0
            displayName: 'Use Node 16.x'
            inputs:
              versionSpec: '16.x'
        
          - script: yarn --frozen-lockfile
            displayName: 'Yarn install package'
          
          - script: yarn build
            displayName: 'Run build'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                **/**
                !**/node_modules/**
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            condition: succeededOrFailed()
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
              ArtifactName: 'drop'

  - stage: upload_static_files
    dependsOn: build
    condition: |
      and(
        in(dependencies.build.result, 'Succeeded', 'SucceededWithIssues'),
        ne(variables['Build.Reason'], 'PullRequest')
      )
    jobs:
      - job: upload_static_files_prd
        displayName: Upload static files in PROD
        condition: contains(variables['Build.SourceBranchName'], 'main')
        steps:
          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWS Pipes'
              regionName: 'us-east-1'
              bucketName: 'dev-mutte0-idp'
              sourceFolder: '$(Pipeline.Workspace)/drop/out'
              globExpressions: '_next/**'
              targetFolder: '$(Build.SourceBranchName)'
              filesAcl: 'public-read'
      - job: upload_static_files_dev
        displayName: Upload static files in DEV
        condition: |
          or(
            contains(variables['Build.SourceBranchName'], 'qa'),
            contains(variables['Build.SourceBranchName'], 'develop')
          )
        steps:
          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWS Pipes'
              regionName: 'us-east-1'
              bucketName: 'dev-mutte0-idp-dev'
              sourceFolder: '$(Pipeline.Workspace)/drop/out'
              globExpressions: '_next/**'
              targetFolder: '$(Build.SourceBranchName)'
              filesAcl: 'public-read'

  - stage: deploy_dev
    dependsOn: upload_static_files
    condition: |
      and(
        in(dependencies.upload_static_files.result, 'Succeeded', 'SucceededWithIssues'),
        contains(variables['Build.SourceBranch'], 'refs/heads/develop')
      )
    jobs:
      - deployment: Deploy
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - task: NodeTool@0
                  displayName: 'Use Node 16.x'
                  inputs:
                    versionSpec: '16.x'

                - script: 'cd $(Pipeline.Workspace)/drop && yarn install --frozen-lockfile'
                  displayName: 'yarn install'

                - script: 'cd $(Pipeline.Workspace)/drop && yarn deploy:auth0'
                  displayName: 'Deploy HTML in Auth0'
                  env:
                    AUTH0_DOMAIN: $(AUTH0_DOMAIN)
                    AUTH0_CLIENT_ID: $(AUTH0_CLIENT_ID)
                    AUTH0_CLIENT_SECRET: $(AUTH0_CLIENT_SECRET)

  - stage: deploy_qa
    dependsOn: upload_static_files
    condition: |
      and(
        in(dependencies.upload_static_files.result, 'Succeeded', 'SucceededWithIssues'),
        contains(variables['Build.SourceBranch'], 'refs/heads/release/qa')
      )
    jobs:
      - deployment: Deploy
        environment: 'qa'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - task: NodeTool@0
                  displayName: 'Use Node 16.x'
                  inputs:
                    versionSpec: '16.x'

                - script: 'cd $(Pipeline.Workspace)/drop && yarn install --frozen-lockfile'
                  displayName: 'yarn install'

                - script: 'cd $(Pipeline.Workspace)/drop && yarn deploy:auth0'
                  displayName: 'Deploy HTML in Auth0'
                  env:
                    AUTH0_DOMAIN: $(AUTH0_DOMAIN)
                    AUTH0_CLIENT_ID: $(AUTH0_CLIENT_ID)
                    AUTH0_CLIENT_SECRET: $(AUTH0_CLIENT_SECRET)

  - stage: deploy_prd
    dependsOn: upload_static_files
    condition: |
      and(
        in(dependencies.upload_static_files.result, 'Succeeded', 'SucceededWithIssues'),
        contains(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
      - deployment: Deploy
        environment: 'prd'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - task: NodeTool@0
                  displayName: 'Use Node 16.x'
                  inputs:
                    versionSpec: '16.x'

                - script: 'cd $(Pipeline.Workspace)/drop && yarn install --frozen-lockfile'
                  displayName: 'yarn install'

                - script: 'cd $(Pipeline.Workspace)/drop && yarn deploy:auth0'
                  displayName: 'Deploy HTML in Auth0'
                  env:
                    AUTH0_DOMAIN: $(AUTH0_DOMAIN)
                    AUTH0_CLIENT_ID: $(AUTH0_CLIENT_ID)
                    AUTH0_CLIENT_SECRET: $(AUTH0_CLIENT_SECRET)
