trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:


  - task: NodeTool@0
    displayName: 'Use Node 16.x'
    inputs:
      versionSpec: '16.x'

  - script: |
      cd auth0-custom-login-deploy
      yarn --frozen-lockfile
      yarn build
    displayName: 'Yarn install and build'

  - task: S3Upload@1
    inputs:
      awsCredentials: 'YOUR_AWS_CONNECTION'
      regionName: 'us-east-1'
      bucketName: 'auth0-custom-login-bucket'
      sourceFolder: '$(Build.SourcesDirectory)/out'
      globExpressions: '_next/**'
